### ISSUE TITLE
Question about embedding vector

### ISSUE THREAD

**Issue by zhanxiuxiu** [lizi-git/Social-Network-Embedding#9]
Hello, 

I want to ask a question about the embedding vector for each user in the graph. Why do you add the weight matrix from the SKipGram model as a part of the final embedding vector (In line 114)?

**Comment by liziliao** [comment]
Hi,

The sum of input and output part vectors is a common operation, which often
results in better results.

Cheers,
Lizi

zhanxiuxiu <notifications@github.com> 于2018年12月12日周三 下午5:39写道：

**Comment by zhanxiuxiu** [comment]
ok, thanks.

Best,
Xiuxiu
